/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./cjs/index.cjs]{@link ./cjs/index.cjs}
 * 
 **/
export const add  = function (a, b)
{
    return a + b;
}

